(defparameter *BR* (list
  ;;La dépression réactionnelle   
  '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(causes_externes_fortes)(vision_futur_négatif )(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(causes_externes_fortes)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
  ;;La dépression endogène
  '(((triste)(perte_emotionnelle)(ralentissement_psychomoteur)(perte_libido)(pas_causes_externes)(intensité_symptomes_forte)(vision_futur_négatif )) "Peinture" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((ralentissement_psychomoteur)(perte_libido)(pas_causes_externes)(intensité_symptomes_forte)(vision_futur_négatif )) "Peinture" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))

  ;;La dépression névrotique
  '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_faible)(sensible_environnement)(causes_externes_faibles)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
  ;;La dépression du post-partum
  '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(acouchement_4_8_semaines)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))

  ;;La dépression de la personne âgée
  '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(maladie)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
  '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
   '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
   '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(mort_conjoint)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  
 '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(vieu_sensible)(faible_famille)(maladie)(vision_futur_négatif )) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))

  ;;La dépression saisonnière
 '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(pas_depressif_en_general)(saison_hiver)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))

  ;;La maniaco-dépression
 '(((triste)(manque_interer)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(manque_interer)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(faible_estime)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_sommeil)(manque_interer)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_concentration)(manque_interer))(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
  '(((triste)(trouble_appetit)(manque_interer)(intensité_symptomes_forte)(discontinue_bipolaire)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))

;;La dépression masquée
   '(((plaintes_régulières)(symptomes_somatiques)(non_symptomes_depressif)) "Photographie" "Evadez vous, capturez et observez mieux l'environnement qui vous entoure !"))
 
))

