;;; import
(load "engine.lisp")

(defun printMenu()
    (terpri)
	(write-line "------ Menu ------")
    (terpri)
	(write-line "1. Lancer le système expert")
	(write-line "2. Sortir du système expert"))
	
(defun printMenuExpertType()
    (terpri)
	(write-line "------ Menu ------")
    (terpri)
	(write-line "1. Lancer une recherche de chaînage arrière")
	(write-line "2. Lancer une recherche de chaînage avant"))

(defun menu()
	(printMenu)
    (terpri)
    (let ((action_1 (read)))
        (if (numberp action_1) 
            (cond 
				((= action_1 1)
					(printMenuExpertType)
					(terpri)
					(let ((action_2 (read)))
					(if (numberp action_2) 
						(cond ((= action_2 1)
							(runEngine 1))
							((= action_2 2)
							(runEngine 2))))))
				((= action_1 2)
					(quit))
    			)
				(write-line "Entrée invalide. Merci d'entrer une valeur proposée dans le menu.")))
	(menu))

;; Lancement :
(format t "~%Bienvenue au cabinet...")
(menu)
