(defparameter sensation_depression 'default)
(defparameter tristesse 'default)
(defparameter faible_interet 'default)
(defparameter trouble 'default)
(defparameter estime_de_soi 'default)
(defparameter evennement_traumatisant 'default)
(defparameter empathie 'default)
(defparameter ralentissement_psychomoteur 'default)
(defparameter libido 'default)
(defparameter intensite 'default)
(defparameter environnement 'default)
(defparameter sexe 'default)
(defparameter nb_acouchement 'default)
(defparameter age 'default)
(defparameter décès 'default)
(defparameter famille 'default)
(defparameter continuite 'default)
(defparameter hiver 'default)
(defparameter saut_humeur 'default)
(defparameter plainte 'default)
(defparameter proche_station 'default)
(defparameter futur 'default)

(defparameter *questions* (list
    '("avez-vous la sensation d'être dépressif ? (oui ou non)" sensation_depression)
    '("Ressentez-vous un sentiment ou des sensations semblables a la tristesse ?(oui ou non)" tristesse)
    '("Avez-vous perte d'intérêt en géneral ?(oui ou non)" faible_interet)
    '("Resentez-vous un trouble en particulier ? (sommeil,appetit ou concentration)" trouble)
    '("Avez-vous faible estime de vous ?(oui ou non)" estime_de_soi)
    '("Avez-vous vécu un évenement traumatisant ? Si oui notez l'importance de celle-ci sur 10 sinon mmettez 0." evennement_traumatisant)
    '("Vous sentez-vous moins empathique ?(oui ou non)" empathie)
    '("Vous sentez-vous plus lent dans vos mouvements ?(oui ou non)" ralentissement_psychomoteur)
    '("Sentez-vous une perte de libido ?(oui ou non)" libido)
    '("Notez sur 10 l'intensité des symptomes que vous avez." intensite)
    '("Etes-vous sensible a votre environnement en termes de réaction émotionnelle ?(oui ou non)" environnement)
    '("Etes-vous un homme ou une femme (homme ou femme)" sexe)                           
    '("Avez-vous accouché ? Si non, mettez 0, si oui depuis combien de mois avez-vous accouché ?" nb_acouchement)
    '("Quel âge avez-vous ?" age)
    '("si vous aviez un conjoint l'avez vous perdu a cause de son décès ?(oui ou non)" décès)
    '("Avez-vous des maladies graves ?(oui ou non)" maladies)
    '("Avez-vous une famille présente pour vous ?(oui ou non)" famille)
    '("Avez-vous constamment ces symptomes ?(oui ou non)" continuite)
    '("Les symptomes vous arrivent-il plus souvent en hiver ?(oui ou non)" hiver)
    '("Avez-vous des sauts d'humeurs ?(oui ou non)" saut_humeur)
    '("Vous plaignez vous souvent ?(oui ou non)" plainte)
    '("Avez-vous des sensations physiques désagréables ?(oui ou non)" proche_station)
    '("Avez-vous une vision du futur négative ?(oui ou non)" futur)
))
