(defparameter *questions* (list
    '("Ressentez-vous un sentiment ou des sensations semblables a la tristesse ?(oui ou non)" 'type_activite)
    '("Avez-vous perte d'intérêt en géneral ?(oui ou non)" 'type_intellectuelle)
    '("Resentez-vous un trouble en particulier ? (sommeil,appetit ou concentration)" 'art)
    '("Avez-vous faible estime de vous ?(oui ou non)" 'reflexion)
    '("Avez-vous vécu un évenement traumatisant ? Si oui notez l'importance de celle-ci sur 10 sinon mmettez 0." 'personnes)
    '("Vous sentez-vous moins empathique ?(oui ou non)" 'type_info)
    '("Vous sentez-vous plus lent dans vos mouvements ?(oui ou non)" 'type_info)
    '("Sentez-vous une perte de libido ?(oui ou non)" 'type_info)
    '("Notez sur 10 l'intensité des symptomes que vous avez." 'personnes)
    '("Etes-vous sensible a votre environnement en termes de réaction émotionnelle ?(oui ou non)" 'type_info)
    '("Etes-vous un homme ou une femme (homme ou femme)" 'personnes)                           
    '("Avez-vous accouché ? Si oui depuis combien de mois avez-vous accouché ?" 'personnes)
    '("Quel âge avez-vous ?" 'type_detente)
    '("Avez-vous des maladies graves ?(oui ou non)" 'type_detente)
    '("Avez-vous une famille présente pour vous ?(oui ou non)" 'type_detente)
    '("Cherchez-vous une activité dans une COURS ou en INTERIEUR ?" 'type_pIntCours)
    '("Quelle particularité préférez-vous parmis FILET, BUT, PANIER ?" 'type_pInterieure)
    '("Cherchez-vous une activité dans AQUATIQUE ou HIVERNALE ?" 'type_pSpeciale)
    '("Etes-vous proche d'une station de ski ? (OUI ou NON)" 'proche_station)
))

