(defparameter *questions* (list
    '("avez-vous la sensation d'être dépressif ? (OUI ou NON)" 'proche_station)
    '("Ressentez-vous un sentiment ou des sensations semblables a la tristesse ?(oui ou non)" 'type_activite)
    '("Avez-vous perte d'intérêt en géneral ?(oui ou non)" 'type_intellectuelle)
    '("Resentez-vous un trouble en particulier ? (sommeil,appetit ou concentration)" 'art)
    '("Avez-vous faible estime de vous ?(oui ou non)" 'reflexion)
    '("Avez-vous vécu un évenement traumatisant ? Si oui notez l'importance de celle-ci sur 10 sinon mmettez 0." 'personnes)
    '("Vous sentez-vous moins empathique ?(oui ou non)" 'type_info)
    '("Vous sentez-vous plus lent dans vos mouvements ?(oui ou non)" 'type_info)
    '("Sentez-vous une perte de libido ?(oui ou non)" 'type_info)
    '("Notez sur 10 l'intensité des symptomes que vous avez." 'personnes)
    '("Etes-vous sensible a votre environnement en termes de réaction émotionnelle ?(oui ou non)" 'type_info)
    '("Etes-vous un homme ou une femme (homme ou femme)" 'personnes)                           
    '("Avez-vous accouché ? Si oui depuis combien de mois avez-vous accouché ?" 'personnes)
    '("Quel âge avez-vous ?" 'type_detente)
    '("Avez-vous des maladies graves ?(oui ou non)" 'type_detente)
    '("Avez-vous une famille présente pour vous ?(oui ou non)" 'type_detente)
    '("Avez-vous constamment ces symptomes ?(oui ou non)" 'type_detente)
    '("Les symptomes vous arrivent-il plus souvent en hiver ?(oui ou non)" 'type_pInterieure)
    '("Avez-vous des sauts d'humeurs ?(oui ou non)" 'type_pSpeciale)
    '("Vous plaignez vous souvent ?(oui ou non)" 'proche_station)
    '("Avez-vous des sensations physiques désagréables ?(oui ou non)" 'proche_station)
    '("Avez-vous une vision du futur négative ?(oui ou non)" 'proche_station)
))
